### ISSUE TITLE
Internal error: Unexpected type PHPStan\Type\ObjectType 

### ISSUE THREAD

**Issue by rz6789** [proget-hq/phpstan-yii2#36]
PHP 7.3.26
 "yiisoft/yii2" : "2.0.30",
"phpstan/phpstan": "0.12.69",
 "proget-hq/phpstan-yii2": "^0.7", 

Internal error: Internal error: Unexpected type PHPStan\Type\ObjectType during method call andFilterWhere at line 139 in file /var/www/promo-api/readModels/goods/TagIndexSearchModel.php  
     Run PHPStan with --debug option and post the stack trace to:                                                                                                                               
     https://github.com/phpstan/phpstan/issues/new                                                                                                                                              
     Internal error: Internal error: Unexpected type PHPStan\Type\ObjectType during method call from at line 251 in file /var/www/promo-api/readModels/promotion/PromotionFilterModel.php       
     Run PHPStan with --debug option and post the stack trace to:                                                                                                                               
     https://github.com/phpstan/phpstan/issues/new                                                                                                                                              
     Internal error: Internal error: Unexpected type PHPStan\Type\ObjectType during method call asArray at line 122 in file /var/www/promo-api/readModels/promotion/PromotionSearchModel.php    
     Run PHPStan with --debug option and post the stack trace to:                                                                                                                               
     https://github.com/phpstan/phpstan/issues/new                                                                                                                                              
     Internal error: Internal error: Unexpected type PHPStan\Type\ObjectType during method call cache at line 93 in file /var/www/promo-api/readModels/promotion/PromotionGoodsSearchModel.php  
     Run PHPStan with --debug option and post the stack trace to:                                                                                                                               
     https://github.com/phpstan/phpstan/issues/new                                                                                                                                              
     Child process error (exit code 1):                                                                                                                                                         
     Child process error (exit code 1):   

with --debug option just show
....
/var/www/promo-api/readModels/goods/TagIndexSearchModel.php
<pre>An internal server error occurred.</pre>

**Comment by EtienneBruines** [comment]
Do you think https://github.com/proget-hq/phpstan-yii2/issues/25 might be related?

**Comment by rz6789** [comment]
yes
looks like problem is in same place
https://github.com/proget-hq/phpstan-yii2/blob/a24ea3f9bb02cfe4e6985cc3c18f0e3e5719fa58/src/Type/ActiveQueryDynamicMethodReturnTypeExtension.php#L44

**Comment by particleflux** [comment]
Any update or workaround for this?

**Comment by marmichalski** [comment]
Closing as a duplicate of #25.

Pull requests are more than welcome 🐱.

**Comment by XMarat** [comment]
I fix it https://github.com/proget-hq/phpstan-yii2/pull/48
