### ISSUE TITLE
String service definitions are considered function

### ISSUE THREAD

**Issue by przepompownia** [proget-hq/phpstan-yii2#37]
For entry
```php
[
    'singletons' => [
        CacheInterface::class => FileCache::class
    ]
]
```
in container configurations I get
```
In ServiceMap.php line 87:
                                                   
  Function yii\caching\FileCache() does not exist
```
because this service definition [is considered function](https://github.com/proget-hq/phpstan-yii2/blob/a24ea3f9bb02cfe4e6985cc3c18f0e3e5719fa58/src/ServiceMap.php#L82).

Probably adding 
```php
        if (\is_string($service) && class_exists($service)) {
            $this->services[$id] = $service;
            return;
        }
```
at the top of `addServiceDefinition()` is enough to resolve this problem.

**Comment by akondas** [comment]
Thanks for reporting. Do you think you are able to open a PR with the required change?
