### ISSUE TITLE
container -> singletons

### ISSUE THREAD

**Issue by Mike-Tranzit** [proget-hq/phpstan-yii2#9]
При анализе появляется ошибка вида:
![image](https://user-images.githubusercontent.com/3366857/49643638-45695680-fa27-11e8-8505-509484d3bb60.png)

Немного покопавшись в коде наткнулся на:
![image](https://user-images.githubusercontent.com/3366857/49643763-a09b4900-fa27-11e8-973f-8b7edad21ae1.png)
Что мы должны добавлять в этот массив в файле конфигурации?

**Comment by FlorinRo** [comment]
That section is to tell the container which classes are singletons
see https://www.yiiframework.com/doc/guide/2.0/en/concept-di-container or https://www.yiiframework.com/doc/guide/2.0/ru/concept-di-container

You can just set it to an empty array if you don't nead it (make sure you define $config['container']['class'] aswell).
I think the phpstan-yii2 code neads to check if the config is empty
```php
    if (! empty($config['container']['singletons'])) {
        foreach ($config['container']['singletons'] as $id => $service) {
            ...
        }
    }
```
